In [1]:
import numpy as np

x = np.arange(16)
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [2]:
x[3]

3

In [3]:
x[3:9]

array([3, 4, 5, 6, 7, 8])

In [4]:
x[3:9:2]

array([3, 5, 7])

In [5]:
[x[3], x[5], x[8]]

[3, 5, 8]

In [6]:
ind = [3, 5, 6]

In [7]:
x[ind]

array([3, 5, 6])

In [8]:
ind = np.array([[0,2], [1, 3]])
x[ind]

array([[0, 2],
       [1, 3]])

In [9]:
X = x.reshape(4, -1)
X

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [11]:
row = np.array([0, 1, 2])
column = np.array([1, 2, 3])
X[row, column]

array([ 1,  6, 11])

In [12]:
X[0, column]

array([1, 2, 3])

In [13]:
X[:, column]

array([[ 1,  2,  3],
       [ 5,  6,  7],
       [ 9, 10, 11],
       [13, 14, 15]])