In [8]:
import numpy as np

In [4]:
print(np.version.version)

1.18.1


### Python list

In [5]:
L = [i for i in range(10)]
L

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [7]:
L[5] = 'ML'
L

[0, 1, 2, 3, 4, 'ML', 6, 7, 8, 9]

In [1]:
import array

In [2]:
arr = array.array('i', [i for i in range(10)])

In [3]:
arr

array('i', [0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
arr[5] = 100

In [5]:
arr

array('i', [0, 1, 2, 3, 4, 100, 6, 7, 8, 9])

In [6]:
arr[4] = 'ML'

TypeError: an integer is required (got type str)

### Numpy.array

In [10]:
nparr = np.array([i for i in range(10)])
nparr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
nparr[5] = 'NL'

ValueError: invalid literal for int() with base 10: 'NL'

In [12]:
nparr.dtype

dtype('int32')

In [13]:
nparr[4] = 5.0

In [14]:
nparr

array([0, 1, 2, 3, 5, 5, 6, 7, 8, 9])

In [15]:
nparr.dtype

dtype('int32')

In [16]:
nparr[3] = 3.15

In [17]:
nparr.dtype

dtype('int32')

In [18]:
nparr

array([0, 1, 2, 3, 5, 5, 6, 7, 8, 9])

In [19]:
nparr2 = np.array([1,2,3.0])
nparr2.dtype

dtype('float64')

In [20]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [21]:
np.zeros(10).dtype

dtype('float64')

In [22]:
np.zeros(10, dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [23]:
np.zeros((3,5), dtype=int)   #arg1 = shape

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [24]:
np.ones((3,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [26]:
np.full(shape = (3, 5),  fill_value = 66)  #arg2 = value

array([[66, 66, 66, 66, 66],
       [66, 66, 66, 66, 66],
       [66, 66, 66, 66, 66]])

## arange

In [27]:
[i for i in range(0,20,2)]   #前闭后开  不能是float

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18]

In [28]:
np.arange(0, 20, 2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [29]:
np.arange(0, 20, 0.2)

array([ 0. ,  0.2,  0.4,  0.6,  0.8,  1. ,  1.2,  1.4,  1.6,  1.8,  2. ,
        2.2,  2.4,  2.6,  2.8,  3. ,  3.2,  3.4,  3.6,  3.8,  4. ,  4.2,
        4.4,  4.6,  4.8,  5. ,  5.2,  5.4,  5.6,  5.8,  6. ,  6.2,  6.4,
        6.6,  6.8,  7. ,  7.2,  7.4,  7.6,  7.8,  8. ,  8.2,  8.4,  8.6,
        8.8,  9. ,  9.2,  9.4,  9.6,  9.8, 10. , 10.2, 10.4, 10.6, 10.8,
       11. , 11.2, 11.4, 11.6, 11.8, 12. , 12.2, 12.4, 12.6, 12.8, 13. ,
       13.2, 13.4, 13.6, 13.8, 14. , 14.2, 14.4, 14.6, 14.8, 15. , 15.2,
       15.4, 15.6, 15.8, 16. , 16.2, 16.4, 16.6, 16.8, 17. , 17.2, 17.4,
       17.6, 17.8, 18. , 18.2, 18.4, 18.6, 18.8, 19. , 19.2, 19.4, 19.6,
       19.8])

## linspace

In [30]:
np.linspace(0 ,20, 10)  #双闭合，arg3为数据个数

array([ 0.        ,  2.22222222,  4.44444444,  6.66666667,  8.88888889,
       11.11111111, 13.33333333, 15.55555556, 17.77777778, 20.        ])

In [31]:
np.linspace(0 ,20, 11) 

array([ 0.,  2.,  4.,  6.,  8., 10., 12., 14., 16., 18., 20.])

## random

In [32]:
np.random.randint(0, 10)  #arg1 from  arg2 to   前闭后开


6

In [34]:
np.random.randint(0, 10, 10)  #arg3 = len(list)

array([4, 1, 8, 3, 0, 8, 5, 2, 5, 5])

In [35]:
np.random.randint(0, 1, 10)  #前闭后开

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [36]:
np.random.randint(4, 8, size = 10)

array([6, 4, 5, 6, 6, 6, 6, 7, 6, 5])

In [38]:
np.random.randint(4, 8, size = (3,5))    #size = tupple   shape

array([[6, 4, 7, 5, 7],
       [4, 6, 6, 7, 5],
       [6, 5, 4, 5, 5]])

In [39]:
np.random.seed(666)
np.random.randint(4, 8, size=(3,4))

array([[4, 6, 5, 6],
       [6, 6, 5, 6],
       [4, 5, 7, 6]])

In [41]:
np.random.seed(666)
np.random.randint(4, 8, size=(3,4))

array([[4, 6, 5, 6],
       [6, 6, 5, 6],
       [4, 5, 7, 6]])

In [42]:
np.random.random()  #form 0-1  dtype = float

0.41358769878652346

In [43]:
np.random.random(size = 10)

array([0.04881279, 0.09992856, 0.50806631, 0.20024754, 0.74415417,
       0.192892  , 0.70084475, 0.29322811, 0.77447945, 0.00510884])

In [44]:
np.random.random(size = (3, 5))

array([[0.11285765, 0.11095367, 0.24766823, 0.0232363 , 0.72732115],
       [0.34003494, 0.19750316, 0.90917959, 0.97834699, 0.53280254],
       [0.25913185, 0.58381262, 0.32569065, 0.88889931, 0.62640453]])

In [45]:
np.random.normal()  #standard normal dist

0.19459960304411825

In [47]:
np.random.normal(0, 10,(3, 5))

array([[ -9.28554011,   2.74608204, -15.30129356,  11.52586796,
         -9.03398446],
       [  1.85628367,   2.0523546 ,   4.79998645,  11.44001244,
         -6.10184167],
       [  2.83441843,  14.32059651,  -4.11855559,  32.17276051,
        -11.14927612]])

In [48]:
np.random.normal?

In [49]:
np.random?

In [50]:
help(np.random.normal)

Help on built-in function normal:

normal(...) method of numpy.random.mtrand.RandomState instance
    normal(loc=0.0, scale=1.0, size=None)
    
    Draw random samples from a normal (Gaussian) distribution.
    
    The probability density function of the normal distribution, first
    derived by De Moivre and 200 years later by both Gauss and Laplace
    independently [2]_, is often called the bell curve because of
    its characteristic shape (see the example below).
    
    The normal distributions occurs often in nature.  For example, it
    describes the commonly occurring distribution of samples influenced
    by a large number of tiny, random disturbances, each with its own
    unique distribution [2]_.
    
    .. note::
        New code should use the ``normal`` method of a ``default_rng()``
        instance instead; see `random-quick-start`.
    
    Parameters
    ----------
    loc : float or array_like of floats
        Mean ("centre") of the distribution.
    scale : fl