In [1]:
import numpy as np

In [9]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
X = np.arange(15).reshape(3, 5)
X

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

## 基本属性:ndim、shape、size

In [10]:
x.ndim

1

In [11]:
x.shape

(10,)

In [12]:
X.ndim

2

In [14]:
X.shape

(3, 5)

In [15]:
x.size

10

In [16]:
X.size

15

## array数据访问

In [17]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [18]:
x[0]

0

In [19]:
X

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [20]:
X[0,0]

0

In [21]:
X[2, 2]

12

In [22]:
 x[:5]

array([0, 1, 2, 3, 4])

In [23]:
x[5:]

array([5, 6, 7, 8, 9])

In [24]:
x[::2]  #arg3  steplen

array([0, 2, 4, 6, 8])

In [25]:
x[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [30]:
x[[0,3,6]]

array([0, 3, 6])

In [31]:
X[:3, :2]

array([[ 0,  1],
       [ 5,  6],
       [10, 11]])

In [33]:
X[:2][:3]

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [34]:
X[:2]

array([0, 1])

In [36]:
X[:2][:3]

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [37]:
X[:2, ::2]

array([[0, 2, 4],
       [5, 7, 9]])

In [38]:
X[::-1, ::-1]

array([[14, 13, 12, 11, 10],
       [ 9,  8,  7,  6,  5],
       [ 4,  3,  2,  1,  0]])

In [39]:
X[0, :]

array([0, 1, 2, 3, 4])

In [41]:
X[:, 0]

array([ 0,  5, 10])

In [43]:
subX = X[:2, :3]
subX

array([[0, 1, 2],
       [5, 6, 7]])

In [44]:
subX[0, 0] = 100
subX

array([[100,   1,   2],
       [  5,   6,   7]])

In [45]:
X  ##对原矩阵进行直接修改，引用方式获得子矩阵而不创建拷贝

array([[100,   1,   2,   3,   4],
       [  5,   6,   7,   8,   9],
       [ 10,  11,  12,  13,  14]])

In [46]:
X[0,0] = 0
X

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [47]:
subX

array([[0, 1, 2],
       [5, 6, 7]])

In [48]:
subX = X[:2, :3].copy()
subX


array([[0, 1, 2],
       [5, 6, 7]])

In [51]:
subX[0, 0]= 100
subX

array([[100,   1,   2],
       [  5,   6,   7]])

In [52]:
X

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

## Reshape

In [53]:
x.shape

(10,)

In [54]:
x.reshape(2,5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [57]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [60]:
A = x.reshape(2, 5)
A.ndim

2

In [61]:
B = x.reshape(1, 10)  #1行仍为2维数组 
B

array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [62]:
B.ndim

2

In [63]:
B.shape

(1, 10)

In [64]:
x.shape

(10,)

In [65]:
x.reshape(10, -1)   #之指定一个维度的数字，另一个维度取-1

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [66]:
x.reshape(-1, 10)

array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [67]:
x.reshape(2, -1)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

## 数据合并

In [2]:
x = np.array([1, 2, 3])
y = np.array([3, 2, 1])

In [3]:
np.concatenate([x, y])

array([1, 2, 3, 3, 2, 1])

In [4]:
z = np.array([666, 66, 666])
np.concatenate([x, y, z])

array([  1,   2,   3,   3,   2,   1, 666,  66, 666])

In [5]:
A = np.array(([1, 2, 3],
                         [4, 5, 6]))

In [6]:
np.concatenate([A, A])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [7]:
np.concatenate([A, A], axis = 1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [8]:
np.concatenate([A, z.reshape(1, -1)])  #-1表示有多少塞多少

array([[  1,   2,   3],
       [  4,   5,   6],
       [666,  66, 666]])

In [9]:
A2 = np.concatenate([A, z.reshape(1, -1)])

In [10]:
np.vstack([A, z])

array([[  1,   2,   3],
       [  4,   5,   6],
       [666,  66, 666]])

In [12]:
B = np.full((2, 2), 100)
B

array([[100, 100],
       [100, 100]])

In [13]:
np.hstack([A, B])

array([[  1,   2,   3, 100, 100],
       [  4,   5,   6, 100, 100]])

## 数据分割

In [15]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [16]:
np.split(x, [3, 7])  #arg2 分割点

[array([0, 1, 2]), array([3, 4, 5, 6]), array([7, 8, 9])]

In [17]:
x1, x2, x3 = np.split(x, [3, 7])

In [18]:
x2

array([3, 4, 5, 6])

In [19]:
np.split(x, [5])

[array([0, 1, 2, 3, 4]), array([5, 6, 7, 8, 9])]

In [20]:
A = np.arange(16).reshape(4, 4)
A

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [21]:
A1, A2 = np.split(A, [2])   #axis = 0 沿着行分割
A1

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [22]:
A2

array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [25]:
A1, A2 = np.split(A, [2], axis = 1)
A1

array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13]])

In [26]:
upper, lower = np.vsplit(A, [2])  #沿着垂直方向按行分割
upper

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [29]:
righer, lefter = np.hsplit(A, [2])
righer

array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13]])

In [30]:
data = np.arange(16).reshape(4, 4)
X, y = np.hsplit(data, [-1])  #最后一列
X

array([[ 0,  1,  2],
       [ 4,  5,  6],
       [ 8,  9, 10],
       [12, 13, 14]])

In [31]:
y

array([[ 3],
       [ 7],
       [11],
       [15]])

In [32]:
y[:, 0]

array([ 3,  7, 11, 15])