In [1]:
import numpy as np
L = np.random.random(100)

In [2]:
L

array([0.10563064, 0.0644243 , 0.61751189, 0.06526868, 0.88881696,
       0.73661411, 0.75118455, 0.66507946, 0.18710214, 0.42090476,
       0.32384594, 0.43742277, 0.11299728, 0.00158606, 0.68829192,
       0.25664779, 0.5490248 , 0.16861087, 0.84717522, 0.43526432,
       0.86757023, 0.61608453, 0.47775858, 0.73409361, 0.65333277,
       0.64953945, 0.06876016, 0.75287877, 0.3842721 , 0.13749131,
       0.38355473, 0.26237685, 0.28904986, 0.25645138, 0.904983  ,
       0.9046257 , 0.88878924, 0.66259126, 0.12675132, 0.50979893,
       0.62223928, 0.06085366, 0.16023834, 0.84207101, 0.18600699,
       0.28030294, 0.62880023, 0.4485546 , 0.21460563, 0.92283172,
       0.84187202, 0.33422932, 0.11505253, 0.63185026, 0.26892481,
       0.16838587, 0.57393403, 0.28104039, 0.57908614, 0.46782675,
       0.82301577, 0.63129293, 0.70148604, 0.97349534, 0.67635794,
       0.22537809, 0.7755147 , 0.93909979, 0.89753387, 0.93312656,
       0.89510478, 0.46379245, 0.22487117, 0.67548674, 0.12923

In [3]:
sum(L)

50.725919738828

In [4]:
np.sum(L)

50.725919738828

In [5]:
big_array = np.random.random(1000000)
%timeit sum(big_array)
%timeit np.sum(big_array)

173 ms ± 2.84 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)
835 µs ± 88.8 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [7]:
np.min(big_array)

2.1202656458330083e-06

In [9]:
np.max(big_array)

0.9999990428770178

In [11]:
X = np.arange(16).reshape(4, -1)
X

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [12]:
np.sum(X)

120

In [14]:
np.sum(X, axis = 1)  #按行,沿着列计算   vsplit 沿着垂直方向按行分割

array([ 6, 22, 38, 54])

In [16]:
np.sum(X, axis = 0) #按列，沿着行  压缩行

array([24, 28, 32, 36])

In [17]:
np.prod(X)

0

In [19]:
np.prod(X+1)

2004189184

In [20]:
np.mean(X)

7.5

In [21]:
np.median(X)

7.5

In [22]:
v = np.array([1, 1, 2, 2, 10])
np.mean(v)

3.2

In [23]:
np.median(v)

2.0

In [24]:
np.percentile(big_array, q = 50)

0.5001072726001273

In [25]:
np.median(big_array)

0.5001072726001273

In [26]:
np.percentile(big_array, q = 100)

0.9999990428770178

In [27]:
np.max(big_array)

0.9999990428770178

In [28]:
for percent in [0, 25, 50, 75, 100]:
    print(np.percentile(big_array, q = percent))

2.1202656458330083e-06
0.24924826373435285
0.5001072726001273
0.7499703251759
0.9999990428770178


In [29]:
np.var(big_array)

0.08338398206176195

In [30]:
np.std(big_array)

0.2887628474401822

In [35]:
x = np.random.normal(0, 1, 1000000)

In [36]:
np.mean(x)

0.0002829841233661229

In [37]:
np.std(x)

1.000455193330108

## 索引

In [39]:
np.min(x)

-4.5456116854374695

In [40]:
np.argmin(x)

51228

In [41]:
x[51228]

-4.5456116854374695

In [42]:
np.argmax(x)

936120

In [43]:
x[936120]

4.60648353727154

In [44]:
np.max(x)

4.60648353727154

## 排序和索引

In [45]:
x = np.arange(16)
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [47]:
np.random.shuffle(x)
x

array([14,  7,  6,  1, 10,  4,  2, 15,  5,  0, 12,  9,  3, 13, 11,  8])

In [48]:
np.sort(x)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [49]:
x

array([14,  7,  6,  1, 10,  4,  2, 15,  5,  0, 12,  9,  3, 13, 11,  8])

In [52]:
x.sort()
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [53]:
X = np.random.randint(10, size=(4,4))
X

array([[9, 4, 6, 3],
       [1, 9, 4, 2],
       [9, 3, 3, 1],
       [3, 4, 6, 7]])

In [54]:
np.sort(X)  #按行排序 axis=1  沿着列排序

array([[3, 4, 6, 9],
       [1, 2, 4, 9],
       [1, 3, 3, 9],
       [3, 4, 6, 7]])

In [55]:
np.sort(X, axis = 0)

array([[1, 3, 3, 1],
       [3, 4, 4, 2],
       [9, 4, 6, 3],
       [9, 9, 6, 7]])

In [56]:
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [59]:
np.random.shuffle(x)
x

array([ 9,  0, 11, 13,  6,  8,  1, 14,  4, 10,  7, 12, 15,  5,  2,  3])

In [60]:
np.argsort(x)  #位置代表排序位置，数字代表原数组中相应对象的索引值

array([ 1,  6, 14, 15,  8, 13,  4, 10,  5,  0,  9,  2, 11,  3,  7, 12],
      dtype=int64)

In [62]:
np.partition(x, 3)  #arg2 标定点 标定点前或后的是无序的

array([ 0,  1,  2,  3,  4,  5,  6,  8,  7,  9, 10, 12, 15, 13, 11, 14])

In [63]:
np.argpartition(x, 3)

array([ 1,  6, 14, 15,  8, 13,  4,  5, 10,  0,  9, 11, 12,  3,  2,  7],
      dtype=int64)

In [64]:
np.argsort(X, axis=1)

array([[3, 1, 2, 0],
       [0, 3, 2, 1],
       [3, 1, 2, 0],
       [0, 1, 2, 3]], dtype=int64)

In [65]:
np.argsort(X, axis=0)

array([[1, 2, 2, 2],
       [3, 0, 1, 1],
       [0, 3, 0, 0],
       [2, 1, 3, 3]], dtype=int64)